{% set version = '0.1-3' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-pki
  version: {{ version|replace("-", "_") }}

source:
  fn: PKI_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/PKI_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/PKI/PKI_{{ version }}.tar.gz
  sha256: 2fcca38b387ecaae6bbfea795f175adb06a21d653c7fceb972fbeb4826410cf6

build:
  merge_build_host: True  # [win]
  number: 2
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}sed               # [win]
    - {{posix}}grep              # [win]
    - {{posix}}autoconf
    - {{posix}}automake          # [not win]
    - {{posix}}automake-wrapper  # [win]
    - {{posix}}pkg-config
    - {{posix}}make
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-base64enc
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-base64enc

test:
  commands:
    - $R -e "library('PKI')"           # [not win]
    - "\"%R%\" -e \"library('PKI')\""  # [win]

about:
  home: http://www.rforge.net/PKI
  license: GPL-2 | GPL-3
  summary: PKI functions such as verifying certificates, RSA encription and signing which can
    be used to build PKI infrastructure and perform cryptographic tasks.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
